definitions:
  api.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  models.Person:
    properties:
      age:
        type: integer
      gender:
        type: string
      id:
        type: string
      name:
        type: string
      nationality:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    type: object
  models.PersonFilters:
    properties:
      age:
        type: integer
      gender:
        type: string
      id:
        type: string
      name:
        type: string
      nationality:
        type: string
      patronymic:
        type: string
      surname:
        type: string
    type: object
info:
  contact: {}
paths:
  /persons:
    get:
      consumes:
      - application/json
      description: Получение списка людей с фильтрами и пагинацией
      parameters:
      - default: 10
        description: Limit
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset
        in: query
        name: offset
        type: integer
      - description: Фильтры
        in: body
        name: filters
        schema:
          $ref: '#/definitions/models.PersonFilters'
      produces:
      - application/json
      responses:
        "200":
          description: Список людей
          schema:
            items:
              $ref: '#/definitions/models.Person'
            type: array
        "400":
          description: Ошибка валидации данных
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Получить список людей
      tags:
      - persons
    post:
      consumes:
      - application/json
      description: Создание нового человека в базе данных
      parameters:
      - description: Новый человек
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/models.Person'
      produces:
      - application/json
      responses:
        "201":
          description: Человек успешно создан
          schema:
            $ref: '#/definitions/models.Person'
        "400":
          description: Ошибка валидации данных
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Создать нового человека
      tags:
      - persons
  /persons/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет человека из базы данных по указанному ID
      parameters:
      - description: ID человека
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: 'Ошибка: ID обязателен'
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Человек не найден
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Удалить человека по ID
      tags:
      - persons
    patch:
      consumes:
      - application/json
      description: Обновляет данные человека по указанному ID. Если поле не указано,
        оно остается без изменений.
      parameters:
      - description: ID человека
        in: path
        name: id
        required: true
        type: string
      - description: Данные для обновления
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/models.Person'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: 'Ошибка: ID обязателен или некорректные данные'
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Человек не найден
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: Обновить информацию о человеке
      tags:
      - persons
swagger: "2.0"
